### ISSUE TITLE
Pokemon Stadium (JPN & USA) Glitches at list

### ISSUE THREAD

**Issue by Santiii733** [DEFAULTDNB/ReCollect64#1]
Heyo! It's happening the error when you select pokemon stadium 1 (Aka pokemon stadium 2 as JPN), at NTSC list. It's from 100% & 101% list issue.

Appears this error msg: [["007 The World is Not Enough U"],["1080° Snowboarding U"],["40 Winks E"],["64 Hanafuda Tenshi no Yakusoku J"],["64 Oozumou J"],["64 Oozumou 2 J"],["64 Trump Collection Alice no Wakuwaku Trump World J"],["64 de Hakken! Tamagotchi Minna de Tamagotchi World J"],["A Bugs Life U"],["AI Shogi 3 J"],["Aero Fighters Assault U"],["AeroGauge U"],["Aidyn Chronicles The First Mage U"],["Air Boarder 64 J"],["All Star Tennis 99 U"],["All-Star Baseball 99 U"],["All-Star Baseball 2000 U"],["All-Star Baseball 2001 U"],["Armorines Project S.W.A.R.M. U"],["Army Men Air Combat U"],["Army Men Sarges Heroes U"],["Army Men Sarges Heroes 2 U"],["Asteroids Hyper 64 U"],["Automobili Lamborghini U","Ucartridge"],["Bakuretsu Muteki Bangaioh J"],["Bakusho Jinsei 64 Mezase! Resort O J"],["Banjo-Kazooie U","Ucartridge"],["Banjo-Tooie U","Ucartridge"],["Bass Masters 2000 U"],["Bass Rush ECOGEAR PowerWorm Championship J"],["Batman Beyond Return of the Joker U"],["BattleTanx U"],["BattleTanx Global Assault U"],["Battlezone Rise of the Black Dogs U"],["Beetle Adventure Racing! U","Ucartridge"],["Big Mountain 2000 U"],["Bio F.R.E.A.K.S. U"],["Blast Corps U"],["Blues Brothers 2000 U","Ucartridge"],["Body Harvest U"],["Bomberman 64 (Japan) J"],["Bomberman 64 U"],["Bomberman 64 The Second Attack! U"],["Bomberman Hero U"],["Bottom of the 9th U"],["Brunswick Circuit Pro Bowling U","Ucartridge"],["Buck Bumble U"],["Bust-A-Move 2 Arcade Edition U"],["Bust-A-Move 99 U"],["California Speed U","Ucartridge"],["Carmageddon 64 U"],["Castlevania U"],["Castlevania Legacy of Darkness U"],["Centre Court Tennis E"],["Chameleon Twist U"],["Chameleon Twist 2 U"],["Charlie Blasts Territory U"],["Chopper Attack U"],["Choro Q 64 2 Hacha Mecha Grand Prix Race J"],["Chou Kuukan Night Pro Yakyuu King J"],["Chou Kuukan Night Pro Yakyuu King 2 J"],...

**Comment by DEFAULTDNB** [comment]
That is the debug message. You can disable it with the toggle on the right underneath the Z trigger.

**Comment by Santiii733** [comment]
https://cdn.discordapp.com/attachments/350069219863298048/1229542876073951292/image.png?ex=66301009&is=661d9b09&hm=120de0f36ca9f337191bff4062240954a3a9fbc8e1c5ef2e5e9399360c7ea7fb&

Also at 101% & 100% lists not appears the Pokemon Stadium 1 from USA (AKA Pokemon 2 at JP), is causing conflict at that lists, at NTSC region list works well
